name: BewegungsPause
favicon: null
layout_spectrum: 0
typography_spectrum: 0.10322841862216592
title: BewegungsPause
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#7e8d93'
    - '#ffffff'
    - '#7a6553'
    - '#e7d7c0'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
