name: BewegungsPause
favicon: null
layout_spectrum: 0.5690371501259506
typography_spectrum: 0.10322841862216592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.40203115344047546
  lightness: 0.20082146837376058
  saturation: 0.7128293022979051
  rhythmicContrast: 0.3122612605802715
purpose: []
