name: BewegungsPause
favicon: null
layout_spectrum: 0.5690371501259506
typography_spectrum: 0.10322841862216592
title: BewegungsPause
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#7e8d93'
    - '#ffffff'
    - '#7a6553'
    - '#e7d7c0'
  brandStrength: 0.5
  lightness: 0.20082146837376058
  saturation: 0.7128293022979051
  rhythmicContrast: 0.3122612605802715
purpose: []
